spring.jpa.hibernate.ddl-auto=validate
cookie.secure=true

spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.ma.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000

spring.data.redis.timeout=10000