spring.jpa.hibernate.ddl-auto=validate
cookie.secure=true

spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.ma.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000

spring.data.redis.timeout=10000
	
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.TiDBDialect
server.port=${PORT}